### ISSUE TITLE
CrashLoopBackoff of out-of-tree cloud-controller-manager from release v1.24.1

### ISSUE THREAD

**Issue by addyess** [kubernetes-sigs/cloud-provider-azure#1843]
#### What happened:
the cloud-controller-manager is stuck in crashloopbackoff

#### What you expected to happen:
Expected it to not do so. 

#### How to reproduce it (as minimally and precisely as possible):
Deployed 2 instances a worker and a controller
Deploy the out-of-tree manifests (cloud-not-manager and cloud-controller-manager) with appropriate secrets filled in

#### Anything else we need to know?:
deployment configuration:
```
   Containers:
    cloud-controller-manager:
     Image:      mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.23.5
     Port:       <none>
     Host Port:  <none>
     Command:
       cloud-controller-manager
     Args:
       --allocate-node-cidrs=true
       --cloud-config=/etc/kubernetes/cloud-config/azure.json
       --cloud-provider=azure
       --cluster-cidr=172.22.0.0/16
       --cluster-name=k8s
       --controllers=*,-cloud-node
       --configure-cloud-routes=true
       --leader-elect=true
       --route-reconciliation-period=10s
       --v=4
       --port=10267
```

associated stack trace logs from the dying Pod
```
sync.(*Cond).Wait(0x20)
    /usr/local/go/src/sync/cond.go:56 +0x8c
golang.org/x/net/http2.(*pipe).Read(0xc0003ee330, {0xc0006b1801, 0x5ff, 0x5ff})
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/golang.org/x/net/http2/pipe.go:76 +0xeb
golang.org/x/net/http2.transportResponseBody.Read({0x0}, {0xc0006b1801, 0x2, 0xc000685cb0})
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/golang.org/x/net/http2/transport.go:2384 +0x85
encoding/json.(*Decoder).refill(0xc000154780)
    /usr/local/go/src/encoding/json/stream.go:165 +0x17f
encoding/json.(*Decoder).readValue(0xc000154780)
    /usr/local/go/src/encoding/json/stream.go:140 +0xbb
encoding/json.(*Decoder).Decode(0xc000154780, {0x1c3d9e0, 0xc0005b9890})
    /usr/local/go/src/encoding/json/stream.go:63 +0x78
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00030fbc0, {0xc000344800, 0x400, 0x400})
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x19c
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0000994f0, 0xc0003c8230, {0x21cd938, 0xc000365d40})
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0xa7
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc00047c160)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x4f
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0006a1b40)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:105 +0x11c
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:76 +0x135

goroutine 178 [select, 1 minutes]:
k8s.io/apimachinery/pkg/util/wait.contextForChannel.func1()
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:301 +0x77
created by k8s.io/apimachinery/pkg/util/wait.contextForChannel
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:300 +0xc8

goroutine 179 [select, 1 minutes]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1()
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:708 +0x1c9
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:691 +0xcf

goroutine 180 [sync.Cond.Wait, 1 minutes]:
sync.runtime_notifyListWait(0xc0004b6c90, 0x1)
    /usr/local/go/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x21d1060)
    /usr/local/go/src/sync/cond.go:56 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc000548c60)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/client-go/util/workqueue/queue.go:157 +0x9e
k8s.io/apiserver/pkg/server/dynamiccertificates.(*ConfigMapCAController).processNextWorkItem(0xc00021ce70)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:230 +0x5e
k8s.io/apiserver/pkg/server/dynamiccertificates.(*ConfigMapCAController).runWorker(...)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:225
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f2c58abc4b8)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x33830b6553741a59, {0x21ac0a0, 0xc00030fc50}, 0x1, 0xc000102360)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x6eef54c7d4c02ac0, 0x3b9aca00, 0x0, 0xf8, 0x1f2b35042fb6cf72)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x436ef088cafa0d9e, 0x0, 0x0)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by k8s.io/apiserver/pkg/server/dynamiccertificates.(*ConfigMapCAController).Run
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:213 +0x3df

goroutine 181 [select, 1 minutes]:
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x21e83f0, 0xc000663800}, 0xc000147ab8, 0x97cd6a)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:658 +0xe7
k8s.io/apimachinery/pkg/util/wait.poll({0x21e83f0, 0xc000663800}, 0x38, 0x97b965, 0xc000173530)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:594 +0x9a
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x21e83f0, 0xc000663800}, 0xfc5022572b4ef74c, 0x398ac8f91ff2a7b2)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:545 +0x49
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x1f4d880699c73458, 0xa6d917edbf7c00ff, 0x8ffddce4e471b533)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:536 +0x7c
created by k8s.io/apiserver/pkg/server/dynamiccertificates.(*ConfigMapCAController).Run
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:216 +0x496

goroutine 182 [select, 1 minutes]:
k8s.io/apimachinery/pkg/util/wait.contextForChannel.func1()
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:301 +0x77
created by k8s.io/apimachinery/pkg/util/wait.contextForChannel
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:300 +0xc8

goroutine 183 [select, 1 minutes]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1()
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:708 +0x1c9
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:691 +0xcf

goroutine 216 [select]:
net/http.(*persistConn).writeLoop(0xc000325b00)
    /usr/local/go/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1748 +0x1e65

goroutine 174 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x21e8428, 0xc00013a000}, 0xc000618060, 0x97cd6a)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:658 +0xe7
k8s.io/apimachinery/pkg/util/wait.poll({0x21e8428, 0xc00013a000}, 0x67, 0x97b991, 0x10)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:594 +0x9a
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfiniteWithContext({0x21e8428, 0xc00013a000}, 0x40d927, 0x203000)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:566 +0x49
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfinite(0x0, 0xc0004e5440)
    /go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:555 +0x46
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*delayedRouteUpdater).run(0xc0005ea810)
    /go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:94 +0x65
created by sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).InitializeCloudFromConfig
    /go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go:617 +0xcef
Stream closed EOF for kube-system/cloud-controller-manager-5d889bfb59-2f2jx (cloud-controller-manager)
```

#### Environment:

- Kubernetes version (use `kubectl version`): v1.24.1
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04

**Comment by feiskyer** [comment]
I think it should be some issues in the cloud config file. Could you grep "error" or "failed" in the logs and share here?
