### ISSUE TITLE
Basic LoadBalancer e2e tests are failing

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#485]
Refer [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/482/pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb/1351816215558885376), a set of e2e tests are failing because of underlying LoadBalancer issue. Related errors from cloud provider are:

```sh
E0120 09:31:32.967968       1 azure_vmss.go:1272] EnsureHostInPool UpdateVMs for VMSS(kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570, k8s-agentpool1-24471974-vmss) failed with error Retriable: false, RetryAfter: 0s, HTTPStatusCode: 0, RawError: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Code="NotFound" Message="Resource /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570/providers/Microsoft.Network/loadBalancers/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570 not found."
E0120 09:31:32.968064       1 azure_loadbalancer.go:188] reconcileLoadBalancer(e2e-tests-service-lb-w6hm2/servicelb-test) failed: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 0, RawError: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Code="NotFound" Message="Resource /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570/providers/Microsoft.Network/loadBalancers/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570 not found."
```

And:

```sh
E0120 13:08:45.866151       1 azure_backoff.go:366] LoadBalancerClient.Delete(kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570-internal) failed: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "LoadBalancerInUseByVirtualMachineScaleSet",
    "message": "Cannot delete load balancer /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570/providers/Microsoft.Network/loadBalancers/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570-internal since its child resources kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570 are in use by virtual machine scale set /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-cc3a10ee-5afd-11eb-932f-72caf4a78570/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-24471974-vmss.",
    "details": []
  }
}
```

Failing tests include:

![image](https://user-images.githubusercontent.com/676637/105302736-55882400-5bf6-11eb-81ed-d61ff48ba9e8.png)

/kind failing-test

**Comment by MirzaSikander** [comment]
This test is failing as well, and is visible in the screen shot above as well, but was missed in the skip pull request.

```
Ensure LoadBalancer 
  should support multiple external services sharing one preset public IP address
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:264
[BeforeEach] Ensure LoadBalancer
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:56
Jan 28 01:24:35.785: INFO: Creating a kubernetes client
Jan 28 01:24:35.785: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:24:35.786: INFO: Creating a test namespace
Jan 28 01:24:35.810: INFO: Creating a kubernetes client
Jan 28 01:24:35.811: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:24:35.858: INFO: Creating deployment servicelb-test
[It] should support multiple external services sharing one preset public IP address
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:264
Jan 28 01:24:35.881: INFO: Creating public IP resource named service-lb-public-remain4de9
Jan 28 01:24:40.668: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:24:50.692: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:00.692: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:10.693: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:20.692: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:30.692: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:40.693: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:25:50.693: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:26:00.694: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:26:10.693: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:26:20.693: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:26:30.696: INFO: Fail to find ingress, retry it in 10 seconds
```

**Comment by MirzaSikander** [comment]
This one also seems problematic:

```
Ensure LoadBalancer 
  should support assigning to specific IP when updating public service
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:86
[BeforeEach] Ensure LoadBalancer
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:56
Jan 28 01:47:32.732: INFO: Creating a kubernetes client
Jan 28 01:47:32.732: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:47:32.734: INFO: Creating a test namespace
Jan 28 01:47:32.758: INFO: Creating a kubernetes client
Jan 28 01:47:32.758: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:47:32.811: INFO: Creating deployment servicelb-test
[It] should support assigning to specific IP when updating public service
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:86
Jan 28 01:47:32.884: INFO: Successfully created LoadBalancer service servicelb-test in namespace e2e-tests-service-lb-w84w4
Jan 28 01:47:32.884: INFO: Creating public IP resource named service-lb-public-none-IP5dc4
Jan 28 01:47:35.712: INFO: PIP to 40.112.171.172
STEP: Waiting for exposure of the original service without assigned lb IP
Jan 28 01:47:35.736: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:47:45.761: INFO: Exposure successfully, get external ip: 13.91.33.43
STEP: Updating service to bound to specific public IP
Jan 28 01:47:45.761: INFO: will update IP to 40.112.171.172
Jan 28 01:47:45.833: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:47:55.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:05.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:15.859: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:25.860: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:35.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:45.859: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:48:55.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:05.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:15.860: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:25.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:35.859: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:45.861: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:49:55.859: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:50:05.858: INFO: still unmatched external IP, retry it in 10s seconds
Jan 28 01:50:15.860: INFO: still unmatched external IP, retry it in 10s seconds
^C
```

**Comment by MirzaSikander** [comment]
This test is panicing

```
------------------------------
Ensure LoadBalancer 
  should support node label `node.kubernetes.io/exclude-from-external-load-balancers`
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:388
[BeforeEach] Ensure LoadBalancer
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:56
Jan 28 01:52:36.087: INFO: Creating a kubernetes client
Jan 28 01:52:36.087: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:52:36.088: INFO: Creating a test namespace
Jan 28 01:52:36.112: INFO: Creating a kubernetes client
Jan 28 01:52:36.113: INFO: Kubernetes configuration file name: /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/_output/k8s-with-custom-ccm-601225c7/kubeconfig/kubeconfig.westus.json
Jan 28 01:52:36.164: INFO: Creating deployment servicelb-test
[It] should support node label `node.kubernetes.io/exclude-from-external-load-balancers`
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:388
STEP: Checking the number of the node pools
STEP: Creating a service to trigger the LB reconcile
Jan 28 01:52:36.279: INFO: Fail to find ingress, retry it in 10 seconds
Jan 28 01:52:46.304: INFO: Exposure successfully, get external ip: 40.112.168.245
STEP: Checking the initial node number in the LB backend pool
Jan 28 01:52:46.304: INFO: Getting public IPs in the resourceGroup mirsikaks
Jan 28 01:52:46.579: INFO: Getting public IP frontend configuration ID
Jan 28 01:52:46.579: INFO: Successfully obtained PIP front config id: /subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/mirsikaks/providers/Microsoft.Network/loadBalancers/k8s-with-custom-ccm-601225c7/frontendIPConfigurations/abbee4bb782734571a19d2ce2ad8fee7
Jan 28 01:52:46.579: INFO: Getting loadBalancer name from pipFrontendConfigurationID
Jan 28 01:52:46.579: INFO: Got loadBalancerName "k8s-with-custom-ccm-601225c7"
Jan 28 01:52:46.579: INFO: Getting loadBalancer
STEP: Labeling node
Jan 28 01:52:46.735: INFO: Getting public IPs in the resourceGroup mirsikaks
Jan 28 01:52:46.811: INFO: Getting public IP frontend configuration ID
Jan 28 01:52:46.811: INFO: Successfully obtained PIP front config id: /subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/mirsikaks/providers/Microsoft.Network/loadBalancers/k8s-with-custom-ccm-601225c7/frontendIPConfigurations/abbee4bb782734571a19d2ce2ad8fee7
Jan 28 01:52:46.811: INFO: Getting loadBalancer name from pipFrontendConfigurationID
Jan 28 01:52:46.811: INFO: Got loadBalancerName "k8s-with-custom-ccm-601225c7"
Jan 28 01:52:46.811: INFO: Getting loadBalancer
Jan 28 01:52:46.862: INFO: There are 1 nodes in the LB backend pool, will retry soon
Jan 28 01:52:56.863: INFO: Getting public IPs in the resourceGroup mirsikaks
Jan 28 01:52:56.938: INFO: Getting public IP frontend configuration ID
Jan 28 01:52:56.938: INFO: Successfully obtained PIP front config id: /subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/mirsikaks/providers/Microsoft.Network/loadBalancers/k8s-with-custom-ccm-601225c7/frontendIPConfigurations/abbee4bb782734571a19d2ce2ad8fee7
Jan 28 01:52:56.938: INFO: Getting loadBalancer name from pipFrontendConfigurationID
Jan 28 01:52:56.938: INFO: Got loadBalancerName "k8s-with-custom-ccm-601225c7"
Jan 28 01:52:56.939: INFO: Getting loadBalancer
E0128 01:52:56.990280   31096 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 29 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b1c760, 0x2cc23d0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1b1c760, 0x2cc23d0)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/cloud-provider-azure/tests/e2e/network.waitForNodesInLBBackendPool.func1(0xc000b0f130, 0xc000c262a0, 0x2540be400)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:431 +0x90
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc000b0f250, 0xc000b0f000, 0x0, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x69
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc00012d380, 0xc000b0f250, 0xc000c261e0, 0x0, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:541 +0x145
k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc00012d380, 0xc000b0f250, 0x0, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:427 +0x87
k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc00012d380, 0xc000b0f250, 0xc00012d380, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:452 +0x73
k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x2540be400, 0x8bb2c97000, 0xc00067b250, 0x1fe9c20, 0x2d2d2c0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:441 +0x4d
sigs.k8s.io/cloud-provider-azure/tests/e2e/network.waitForNodesInLBBackendPool(0xc000e00580, 0xc00066ef90, 0xe, 0x0, 0x0, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:428 +0x97
sigs.k8s.io/cloud-provider-azure/tests/e2e/network.glob..func1.10()
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:414 +0xa72
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000055320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xa3
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000055320, 0xc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0xd7
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc00000e460, 0x1fbb280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0x67
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000147e00, 0x0, 0x1fbb280, 0xc00003c980)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:215 +0x691
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000147e00, 0x1fbb280, 0xc00003c980)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0xf2
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc0000e6a00, 0xc000147e00, 0x0)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x111
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc0000e6a00, 0x1)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x127
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0000e6a00, 0xc00001aa78)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0000a8280, 0x7f8cc079ee78, 0xc000382f00, 0x1da6884, 0x1e, 0xc00000f780, 0x2, 0x2, 0x2007260, 0xc00003c980, ...)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x426
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x1fbca60, 0xc000382f00, 0x1da6884, 0x1e, 0xc00000f760, 0x2, 0x2, 0x2)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:226 +0x238
github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x1fbca60, 0xc000382f00, 0x1da6884, 0x1e, 0xc00040e890, 0x1, 0x1, 0x1)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:214 +0xad
sigs.k8s.io/cloud-provider-azure/tests/e2e.TestAzureTest(0xc000382f00)
        /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/e2e_test.go:69 +0x116
testing.tRunner(0xc000382f00, 0x1e656e0)
        /usr/lib/go-1.15/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/lib/go-1.15/src/testing/testing.go:1168 +0x2b3
[AfterEach] Ensure LoadBalancer
  /home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:73
Jan 28 01:52:57.017: INFO: Deleting namespace e2e-tests-service-lb-ng9fr
```

**Comment by MirzaSikander** [comment]
```
[Panic!] Ensure LoadBalancer [It] should support node label `node.kubernetes.io/exclude-from-external-load-balancers` 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55

[Fail] Service with annotation [It] should support service annotation 'service.beta.kubernetes.io/azure-load-balancer-resource-group' 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/utils/resource_group_utils.go:36

[Fail] Service with annotation [It] should support service annotation `service.beta.kubernetes.io/azure-pip-name` 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:409

[Fail] Network security group [It] should add the rule when expose a service 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/network_security_group.go:120

[Fail] Ensure LoadBalancer [It] should have no operation since no change in service when update [Slow] 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/ensureloadbalancer.go:250

[Fail] Service with annotation [It] should support service annotation 'service.beta.kubernetes.io/azure-dns-label-name' 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:149

[Fail] [StandardLoadBalancer] Standard load balancer [It] should make outbound IP of pod same as in SLB's outbound rules 
/home/mirsik/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/standard_lb.go:160
```

Are these expected?
