### ISSUE TITLE
Unexpected cloud provider crash when creating LoadBalancer typed service (1.20/1.21)

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#634]
**What happened**:

When creating LoadBalancer typed service and the public IP address hasn't allocated yet, cloud provider azure may panic because of missing a [nil pointer check](https://github.com/kubernetes/legacy-cloud-providers/blob/bd05d48678e698ebffe0c34fb1e003d6d6ec2a37/azure/azure_standard.go#L369-L371).

Refer the example panic stack below:

```
E0505 10:44:43.503818       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2467 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x40c2640, 0x72b6590)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x40c2640, 0x72b6590)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).serviceOwnsFrontendIP(0xc000198a00, 0x0, 0xc00027eee0, 0xc00134b6c0, 0xc00134b6e0, 0xc00134b6f0, 0x0, 0xc00134b6d0, 0xc00107d500, 0x60920000, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go:370 +0x2a2
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancerStatus(0xc000198a00, 0xc00107d500, 0xc001ed2910, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:511 +0x3a5
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancer(0xc000198a00, 0xc00107d500, 0x7ffd2fd0d6d0, 0x16, 0xc000b7c3a0, 0x3, 0x4, 0x1, 0xc000b7c3e0, 0x2, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:383 +0x3e5
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).reconcileLoadBalancer(0xc000198a00, 0x7ffd2fd0d6d0, 0x16, 0xc00107d500, 0xc000b7c3a0, 0x3, 0x4, 0x1, 0x0, 0x0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:1091 +0x409
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).EnsureLoadBalancer(0xc000198a00, 0x5068448, 0xc0001a2008, 0x7ffd2fd0d6d0, 0x16, 0xc00107d500, 0xc000b7c3a0, 0x3, 0x4, 0x0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:187 +0x365
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).ensureLoadBalancer(0xc0004d0000, 0xc00107d500, 0x0, 0x0, 0x6)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:452 +0xf3
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncLoadBalancerIfNeeded(0xc0004d0000, 0xc00107d500, 0xc001a937c0, 0x10, 0xc000b7c360, 0xc0024a2cd0, 0x15a5a93)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:407 +0x9ab
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processServiceCreateOrUpdate(0xc0004d0000, 0xc00107d500, 0xc001a937c0, 0x10, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:343 +0xdf
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncService(0xc0004d0000, 0xc001a937c0, 0x10, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:854 +0x325
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processNextWorkItem(0xc0004d0000, 0x203000)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:301 +0xf5
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).worker(...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:280
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00249dc80)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00249dc80, 0x5007fe0, 0xc001b16420, 0x4b22501, 0xc0007038c0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00249dc80, 0x3b9aca00, 0x0, 0x1, 0xc0007038c0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00249dc80, 0x3b9aca00, 0xc0007038c0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).Run
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:238 +0x24e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x32b9022]
```

**Impacted versions**:

- v1.20.0-v1.20.7
- v1.21.0-v1.21.1

**When would it be fixed**:

- Fixes in out-of-tree cloud provider has been merged https://github.com/kubernetes-sigs/cloud-provider-azure/pull/615 and released as part of v1.0.0.
- Fixes in k/k https://github.com/kubernetes/kubernetes/pull/101739 and would be cherry-picked to 1.20/1.21 branch

**Comment by nilo19** [comment]
the fix has been merged.
/close
